// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASmYb0IGMPoxPykgS6EPN3yMf1wiKoY_k',
    appId: '1:806361009079:web:4e03afc291059c604e7632',
    messagingSenderId: '806361009079',
    projectId: 'appqltbyt-1254f',
    authDomain: 'appqltbyt-1254f.firebaseapp.com',
    storageBucket: 'appqltbyt-1254f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIFjsyEk4rKoMH4DRM9et1HbFsXWKEOgQ',
    appId: '1:806361009079:android:87ab0d6029ee310f4e7632',
    messagingSenderId: '806361009079',
    projectId: 'appqltbyt-1254f',
    storageBucket: 'appqltbyt-1254f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCeZaUkL86LUhctvBDUrQpMfbvAWV3Be8',
    appId: '1:806361009079:ios:325adb223dafe1e74e7632',
    messagingSenderId: '806361009079',
    projectId: 'appqltbyt-1254f',
    storageBucket: 'appqltbyt-1254f.appspot.com',
    iosBundleId: 'com.example.appdemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCeZaUkL86LUhctvBDUrQpMfbvAWV3Be8',
    appId: '1:806361009079:ios:a0071a56081329074e7632',
    messagingSenderId: '806361009079',
    projectId: 'appqltbyt-1254f',
    storageBucket: 'appqltbyt-1254f.appspot.com',
    iosBundleId: 'com.example.appdemo.RunnerTests',
  );
}
